#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Checking code style...'

# Check ESLint 
echo 'ESLint checking...'

npm run lint || 
(
  echo 'Your code has some lint errors. Use `lint-and-format` to fix that and try again';
  false;
)

# Check prettier
echo 'Prettier checking...'

npm run prettier:check ||
(
  echo 'Your code has some prettier errors. Use `lint-and-format` to fix that and try again';
  false;
)

# Check types
echo 'Types checking...'

npm run check-types ||
(
  echo 'Your code has some types errors. Fix them and try to commit again';
  false;
)

# If everuthing passes
echo 'This is a great commit!!!'
